# Generated by Django 4.1 on 2022-08-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbio',
            name='age',
        ),
        migrations.AddField(
            model_name='patientbio',
            name='DOE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
