# Generated by Django 4.1 on 2022-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_medication_healthdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={'verbose_name_plural': 'HealthData'},
        ),
        migrations.AlterModelOptions(
            name='patientbio',
            options={'verbose_name': 'PatientBio', 'verbose_name_plural': 'PatientData'},
        ),
    ]
